### PR TITLE
Seekless

### PR DESCRIPTION
**Pull request by Firtzberg**
Adds data to zipstream without rewinding.
Using this data from s3 is not streamed multiple times.

Requires improvements on file size estimation.

### CODE REVIEW

**Comment by jszobody** [comment]
This looks really intriguing, thanks! Two things offhand:

1) Can you explain your S3 comment? The S3File class currently uses a separate API call to find the filesize, it doesn't seek to find that. So I'm not sure by the "streamed multiple times" remark. It shouldn't be streaming multiple times anyway?

https://github.com/stechstudio/laravel-zipstream/blob/231d722ba41ffc60dc97bf1b43282a3c17ff8bf2/src/Models/S3File.php#L34-L40

2) Your filesize calculation logic looks sounds, but it would be good to get some test coverage on this. Can you write a test class that builds a zip (from small text files created in /tmp, for example), saves the zip, and verifies filesize calculations were accurate?

**Comment by jszobody** [comment]
The second question should have been on the #11 Filesize pull request, let's get test coverage on that PR and I'll merge it, then we can move forward with these other PRs.

This is great stuff, thank you. 👍

**Comment by Firtzberg** [comment]
Thank you for the quick feedback.
You're right, the filesize for S3 files is available upfront. Except the filesize you also need the CRC32. That goes into the local file header (before the file data) which is why the underlying ZipStream-PHP implementation rewinds the S3 stream.
This can be avoided using the zeroHeader flag, in which case the crc goes into the data descriptor.

**Comment by Firtzberg** [comment]
I don't have a Mac, so please try the generated zips.
Based on the ZipStream-PHP README the Mac OS issues appear to be related to the enableZip64 flag.

**Comment by jszobody** [comment]
So now that #11 is merged, this PR just has the one line that enables zeroHeader by default. And yet this causes a test to fail:

```
1) STS\ZipStream\Tests\ZipTest::testSaveZipOutput
Failed asserting that 423 matches expected 335.
```

Thoughts?

**Comment by Firtzberg** [comment]
Yes, I spotted this before.
When you save or download a file the ZipStream->finish() method is called. This clears the archive options. So the setting you applied in the ServiceProvider just get flushed away.
So you have to get the size estimation before processing the archive. You'll see that I did that in the merged PR to prevent raising of false positive ZipSizePredictionFailed events.

**Comment by Firtzberg** [comment]
Have a look at my last commit here to see what I mean. It's fixed now.

**Pull request merged**
