### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by toto4ds**
Added information about `setS3Client()` and `setFilesize`

### CODE REVIEW

**Comment by jszobody** [comment]
This is incorrect:

```php
Zip::create("package.zip")
    ->add("s3://bucket-name/path/to/object.pdf")->setS3Client($s3);
```

The `Zip::add` method returns the `$zip` instance, you can't use `setS3Client` from there. You have to make the `S3File` module and add that, so that you can access the `setS3Client` method:

```php
Zip::create("package.zip")->add(
    S3File::make("s3://bucket-name/path/to/object.pdf")->setS3Client($s3)
);
``

**Comment by toto4ds** [comment]
Oh, I was so worried about the text that I forgot to double-check the code. Are there any comments on the text?

**Comment by jszobody** [comment]
I fixed the code and added a bit more explanation. Thanks for prompting this!

**Comment by toto4ds** [comment]
Thank you, the documentation is much better than mine.

**Pull request merged**
